// Generated by gencpp from file bulletsim_msgs/Face.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_FACE_H
#define BULLETSIM_MSGS_MESSAGE_FACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct Face_
{
  typedef Face_<ContainerAllocator> Type;

  Face_()
    : vertex_inds()
    , normal_inds()  {
    }
  Face_(const ContainerAllocator& _alloc)
    : vertex_inds(_alloc)
    , normal_inds(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _vertex_inds_type;
  _vertex_inds_type vertex_inds;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _normal_inds_type;
  _normal_inds_type normal_inds;





  typedef boost::shared_ptr< ::bulletsim_msgs::Face_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::Face_<ContainerAllocator> const> ConstPtr;

}; // struct Face_

typedef ::bulletsim_msgs::Face_<std::allocator<void> > Face;

typedef boost::shared_ptr< ::bulletsim_msgs::Face > FacePtr;
typedef boost::shared_ptr< ::bulletsim_msgs::Face const> FaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::Face_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::Face_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::Face_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::Face_<ContainerAllocator2> & rhs)
{
  return lhs.vertex_inds == rhs.vertex_inds &&
    lhs.normal_inds == rhs.normal_inds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::Face_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::Face_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::Face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::Face_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::Face_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::Face_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::Face_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::Face_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5aceb6eb38fe514b1014b9171710143e";
  }

  static const char* value(const ::bulletsim_msgs::Face_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5aceb6eb38fe514bULL;
  static const uint64_t static_value2 = 0x1014b9171710143eULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/Face";
  }

  static const char* value(const ::bulletsim_msgs::Face_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] vertex_inds\n"
"uint32[] normal_inds\n"
;
  }

  static const char* value(const ::bulletsim_msgs::Face_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::Face_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vertex_inds);
      stream.next(m.normal_inds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Face_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::Face_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::Face_<ContainerAllocator>& v)
  {
    s << indent << "vertex_inds[]" << std::endl;
    for (size_t i = 0; i < v.vertex_inds.size(); ++i)
    {
      s << indent << "  vertex_inds[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.vertex_inds[i]);
    }
    s << indent << "normal_inds[]" << std::endl;
    for (size_t i = 0; i < v.normal_inds.size(); ++i)
    {
      s << indent << "  normal_inds[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.normal_inds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_FACE_H
