// Generated by gencpp from file bulletsim_msgs/GetTable.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_GETTABLE_H
#define BULLETSIM_MSGS_MESSAGE_GETTABLE_H

#include <ros/service_traits.h>


#include <bulletsim_msgs/GetTableRequest.h>
#include <bulletsim_msgs/GetTableResponse.h>


namespace bulletsim_msgs
{

struct GetTable
{

typedef GetTableRequest Request;
typedef GetTableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTable
} // namespace bulletsim_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bulletsim_msgs::GetTable > {
  static const char* value()
  {
    return "afe2ee72497f9b4d6a6580170d3eac15";
  }

  static const char* value(const ::bulletsim_msgs::GetTable&) { return value(); }
};

template<>
struct DataType< ::bulletsim_msgs::GetTable > {
  static const char* value()
  {
    return "bulletsim_msgs/GetTable";
  }

  static const char* value(const ::bulletsim_msgs::GetTable&) { return value(); }
};


// service_traits::MD5Sum< ::bulletsim_msgs::GetTableRequest> should match
// service_traits::MD5Sum< ::bulletsim_msgs::GetTable >
template<>
struct MD5Sum< ::bulletsim_msgs::GetTableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bulletsim_msgs::GetTable >::value();
  }
  static const char* value(const ::bulletsim_msgs::GetTableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bulletsim_msgs::GetTableRequest> should match
// service_traits::DataType< ::bulletsim_msgs::GetTable >
template<>
struct DataType< ::bulletsim_msgs::GetTableRequest>
{
  static const char* value()
  {
    return DataType< ::bulletsim_msgs::GetTable >::value();
  }
  static const char* value(const ::bulletsim_msgs::GetTableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bulletsim_msgs::GetTableResponse> should match
// service_traits::MD5Sum< ::bulletsim_msgs::GetTable >
template<>
struct MD5Sum< ::bulletsim_msgs::GetTableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bulletsim_msgs::GetTable >::value();
  }
  static const char* value(const ::bulletsim_msgs::GetTableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bulletsim_msgs::GetTableResponse> should match
// service_traits::DataType< ::bulletsim_msgs::GetTable >
template<>
struct DataType< ::bulletsim_msgs::GetTableResponse>
{
  static const char* value()
  {
    return DataType< ::bulletsim_msgs::GetTable >::value();
  }
  static const char* value(const ::bulletsim_msgs::GetTableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_GETTABLE_H
