// Generated by gencpp from file bulletsim_msgs/GetTableRequest.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_GETTABLEREQUEST_H
#define BULLETSIM_MSGS_MESSAGE_GETTABLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct GetTableRequest_
{
  typedef GetTableRequest_<ContainerAllocator> Type;

  GetTableRequest_()
    {
    }
  GetTableRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTableRequest_

typedef ::bulletsim_msgs::GetTableRequest_<std::allocator<void> > GetTableRequest;

typedef boost::shared_ptr< ::bulletsim_msgs::GetTableRequest > GetTableRequestPtr;
typedef boost::shared_ptr< ::bulletsim_msgs::GetTableRequest const> GetTableRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::bulletsim_msgs::GetTableRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/GetTableRequest";
  }

  static const char* value(const ::bulletsim_msgs::GetTableRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::bulletsim_msgs::GetTableRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTableRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::GetTableRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::bulletsim_msgs::GetTableRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_GETTABLEREQUEST_H
