// Generated by gencpp from file bulletsim_msgs/GetTableResponse.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_GETTABLERESPONSE_H
#define BULLETSIM_MSGS_MESSAGE_GETTABLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct GetTableResponse_
{
  typedef GetTableResponse_<ContainerAllocator> Type;

  GetTableResponse_()
    : poly()  {
    }
  GetTableResponse_(const ContainerAllocator& _alloc)
    : poly(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _poly_type;
  _poly_type poly;





  typedef boost::shared_ptr< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTableResponse_

typedef ::bulletsim_msgs::GetTableResponse_<std::allocator<void> > GetTableResponse;

typedef boost::shared_ptr< ::bulletsim_msgs::GetTableResponse > GetTableResponsePtr;
typedef boost::shared_ptr< ::bulletsim_msgs::GetTableResponse const> GetTableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.poly == rhs.poly;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afe2ee72497f9b4d6a6580170d3eac15";
  }

  static const char* value(const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafe2ee72497f9b4dULL;
  static const uint64_t static_value2 = 0x6a6580170d3eac15ULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/GetTableResponse";
  }

  static const char* value(const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PolygonStamped poly\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poly);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::GetTableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::GetTableResponse_<ContainerAllocator>& v)
  {
    s << indent << "poly: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.poly);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_GETTABLERESPONSE_H
