// Generated by gencpp from file bulletsim_msgs/Initialization.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_INITIALIZATION_H
#define BULLETSIM_MSGS_MESSAGE_INITIALIZATION_H

#include <ros/service_traits.h>


#include <bulletsim_msgs/InitializationRequest.h>
#include <bulletsim_msgs/InitializationResponse.h>


namespace bulletsim_msgs
{

struct Initialization
{

typedef InitializationRequest Request;
typedef InitializationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Initialization
} // namespace bulletsim_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bulletsim_msgs::Initialization > {
  static const char* value()
  {
    return "ce0a7e8348fab2f5858b6d6d77cf8ff2";
  }

  static const char* value(const ::bulletsim_msgs::Initialization&) { return value(); }
};

template<>
struct DataType< ::bulletsim_msgs::Initialization > {
  static const char* value()
  {
    return "bulletsim_msgs/Initialization";
  }

  static const char* value(const ::bulletsim_msgs::Initialization&) { return value(); }
};


// service_traits::MD5Sum< ::bulletsim_msgs::InitializationRequest> should match
// service_traits::MD5Sum< ::bulletsim_msgs::Initialization >
template<>
struct MD5Sum< ::bulletsim_msgs::InitializationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bulletsim_msgs::Initialization >::value();
  }
  static const char* value(const ::bulletsim_msgs::InitializationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bulletsim_msgs::InitializationRequest> should match
// service_traits::DataType< ::bulletsim_msgs::Initialization >
template<>
struct DataType< ::bulletsim_msgs::InitializationRequest>
{
  static const char* value()
  {
    return DataType< ::bulletsim_msgs::Initialization >::value();
  }
  static const char* value(const ::bulletsim_msgs::InitializationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bulletsim_msgs::InitializationResponse> should match
// service_traits::MD5Sum< ::bulletsim_msgs::Initialization >
template<>
struct MD5Sum< ::bulletsim_msgs::InitializationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bulletsim_msgs::Initialization >::value();
  }
  static const char* value(const ::bulletsim_msgs::InitializationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bulletsim_msgs::InitializationResponse> should match
// service_traits::DataType< ::bulletsim_msgs::Initialization >
template<>
struct DataType< ::bulletsim_msgs::InitializationResponse>
{
  static const char* value()
  {
    return DataType< ::bulletsim_msgs::Initialization >::value();
  }
  static const char* value(const ::bulletsim_msgs::InitializationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_INITIALIZATION_H
