// Generated by gencpp from file bulletsim_msgs/InitializationResponse.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_INITIALIZATIONRESPONSE_H
#define BULLETSIM_MSGS_MESSAGE_INITIALIZATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bulletsim_msgs/ObjectInit.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct InitializationResponse_
{
  typedef InitializationResponse_<ContainerAllocator> Type;

  InitializationResponse_()
    : objectInit()  {
    }
  InitializationResponse_(const ContainerAllocator& _alloc)
    : objectInit(_alloc)  {
  (void)_alloc;
    }



   typedef  ::bulletsim_msgs::ObjectInit_<ContainerAllocator>  _objectInit_type;
  _objectInit_type objectInit;





  typedef boost::shared_ptr< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitializationResponse_

typedef ::bulletsim_msgs::InitializationResponse_<std::allocator<void> > InitializationResponse;

typedef boost::shared_ptr< ::bulletsim_msgs::InitializationResponse > InitializationResponsePtr;
typedef boost::shared_ptr< ::bulletsim_msgs::InitializationResponse const> InitializationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.objectInit == rhs.objectInit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad576ba0aae0e7f210a9db85d4d9e15d";
  }

  static const char* value(const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad576ba0aae0e7f2ULL;
  static const uint64_t static_value2 = 0x10a9db85d4d9e15dULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/InitializationResponse";
  }

  static const char* value(const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ObjectInit objectInit\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/ObjectInit\n"
"string type\n"
"Rope rope\n"
"Box box\n"
"geometry_msgs/PolygonStamped towel_corners\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Rope\n"
"Header header\n"
"geometry_msgs/Point[] nodes\n"
"float32 radius\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Box\n"
"geometry_msgs/Point center\n"
"geometry_msgs/Point extents\n"
"float32 angle\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objectInit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitializationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::InitializationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::InitializationResponse_<ContainerAllocator>& v)
  {
    s << indent << "objectInit: ";
    s << std::endl;
    Printer< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >::stream(s, indent + "  ", v.objectInit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_INITIALIZATIONRESPONSE_H
