// Generated by gencpp from file bulletsim_msgs/ObjectInit.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_OBJECTINIT_H
#define BULLETSIM_MSGS_MESSAGE_OBJECTINIT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bulletsim_msgs/Rope.h>
#include <bulletsim_msgs/Box.h>
#include <geometry_msgs/PolygonStamped.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct ObjectInit_
{
  typedef ObjectInit_<ContainerAllocator> Type;

  ObjectInit_()
    : type()
    , rope()
    , box()
    , towel_corners()  {
    }
  ObjectInit_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , rope(_alloc)
    , box(_alloc)
    , towel_corners(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef  ::bulletsim_msgs::Rope_<ContainerAllocator>  _rope_type;
  _rope_type rope;

   typedef  ::bulletsim_msgs::Box_<ContainerAllocator>  _box_type;
  _box_type box;

   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _towel_corners_type;
  _towel_corners_type towel_corners;





  typedef boost::shared_ptr< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInit_

typedef ::bulletsim_msgs::ObjectInit_<std::allocator<void> > ObjectInit;

typedef boost::shared_ptr< ::bulletsim_msgs::ObjectInit > ObjectInitPtr;
typedef boost::shared_ptr< ::bulletsim_msgs::ObjectInit const> ObjectInitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::ObjectInit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::ObjectInit_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::ObjectInit_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.rope == rhs.rope &&
    lhs.box == rhs.box &&
    lhs.towel_corners == rhs.towel_corners;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::ObjectInit_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::ObjectInit_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6385cb06dcc1ad81473bbced10d4b931";
  }

  static const char* value(const ::bulletsim_msgs::ObjectInit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6385cb06dcc1ad81ULL;
  static const uint64_t static_value2 = 0x473bbced10d4b931ULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/ObjectInit";
  }

  static const char* value(const ::bulletsim_msgs::ObjectInit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n"
"Rope rope\n"
"Box box\n"
"geometry_msgs/PolygonStamped towel_corners\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Rope\n"
"Header header\n"
"geometry_msgs/Point[] nodes\n"
"float32 radius\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Box\n"
"geometry_msgs/Point center\n"
"geometry_msgs/Point extents\n"
"float32 angle\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::bulletsim_msgs::ObjectInit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.rope);
      stream.next(m.box);
      stream.next(m.towel_corners);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::ObjectInit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::ObjectInit_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "rope: ";
    s << std::endl;
    Printer< ::bulletsim_msgs::Rope_<ContainerAllocator> >::stream(s, indent + "  ", v.rope);
    s << indent << "box: ";
    s << std::endl;
    Printer< ::bulletsim_msgs::Box_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
    s << indent << "towel_corners: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.towel_corners);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_OBJECTINIT_H
