// Generated by gencpp from file bulletsim_msgs/OWLMarker.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_OWLMARKER_H
#define BULLETSIM_MSGS_MESSAGE_OWLMARKER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct OWLMarker_
{
  typedef OWLMarker_<ContainerAllocator> Type;

  OWLMarker_()
    : id(0)
    , frame(0)
    , point()
    , cond(0.0)
    , flag(0)  {
    }
  OWLMarker_(const ContainerAllocator& _alloc)
    : id(0)
    , frame(0)
    , point(_alloc)
    , cond(0.0)
    , flag(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _frame_type;
  _frame_type frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef float _cond_type;
  _cond_type cond;

   typedef uint32_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> const> ConstPtr;

}; // struct OWLMarker_

typedef ::bulletsim_msgs::OWLMarker_<std::allocator<void> > OWLMarker;

typedef boost::shared_ptr< ::bulletsim_msgs::OWLMarker > OWLMarkerPtr;
typedef boost::shared_ptr< ::bulletsim_msgs::OWLMarker const> OWLMarkerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::OWLMarker_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::OWLMarker_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::OWLMarker_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.frame == rhs.frame &&
    lhs.point == rhs.point &&
    lhs.cond == rhs.cond &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::OWLMarker_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::OWLMarker_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "109bc2da4c65dd1a28bff573840d64e2";
  }

  static const char* value(const ::bulletsim_msgs::OWLMarker_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x109bc2da4c65dd1aULL;
  static const uint64_t static_value2 = 0x28bff573840d64e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/OWLMarker";
  }

  static const char* value(const ::bulletsim_msgs::OWLMarker_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#OWLMarker\n"
"int32 id\n"
"int32 frame\n"
"geometry_msgs/Point point\n"
"float32 cond\n"
"uint32 flag\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bulletsim_msgs::OWLMarker_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.frame);
      stream.next(m.point);
      stream.next(m.cond);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OWLMarker_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::OWLMarker_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "frame: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "cond: ";
    Printer<float>::stream(s, indent + "  ", v.cond);
    s << indent << "flag: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_OWLMARKER_H
