// Generated by gencpp from file bulletsim_msgs/OWLPhasespace.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_OWLPHASESPACE_H
#define BULLETSIM_MSGS_MESSAGE_OWLPHASESPACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <bulletsim_msgs/OWLMarker.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct OWLPhasespace_
{
  typedef OWLPhasespace_<ContainerAllocator> Type;

  OWLPhasespace_()
    : header()
    , markers()  {
    }
  OWLPhasespace_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >> _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> const> ConstPtr;

}; // struct OWLPhasespace_

typedef ::bulletsim_msgs::OWLPhasespace_<std::allocator<void> > OWLPhasespace;

typedef boost::shared_ptr< ::bulletsim_msgs::OWLPhasespace > OWLPhasespacePtr;
typedef boost::shared_ptr< ::bulletsim_msgs::OWLPhasespace const> OWLPhasespaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49a94742af886c9cc9b920374e73d647";
  }

  static const char* value(const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49a94742af886c9cULL;
  static const uint64_t static_value2 = 0xc9b920374e73d647ULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/OWLPhasespace";
  }

  static const char* value(const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#OWLPhasespace\n"
"Header header\n"
"OWLMarker[] markers\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/OWLMarker\n"
"#OWLMarker\n"
"int32 id\n"
"int32 frame\n"
"geometry_msgs/Point point\n"
"float32 cond\n"
"uint32 flag\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OWLPhasespace_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::OWLPhasespace_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::bulletsim_msgs::OWLMarker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_OWLPHASESPACE_H
