// Generated by gencpp from file bulletsim_msgs/PlanTraj.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_PLANTRAJ_H
#define BULLETSIM_MSGS_MESSAGE_PLANTRAJ_H

#include <ros/service_traits.h>


#include <bulletsim_msgs/PlanTrajRequest.h>
#include <bulletsim_msgs/PlanTrajResponse.h>


namespace bulletsim_msgs
{

struct PlanTraj
{

typedef PlanTrajRequest Request;
typedef PlanTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanTraj
} // namespace bulletsim_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bulletsim_msgs::PlanTraj > {
  static const char* value()
  {
    return "99d192cef3d7416d1c568b72205fe94b";
  }

  static const char* value(const ::bulletsim_msgs::PlanTraj&) { return value(); }
};

template<>
struct DataType< ::bulletsim_msgs::PlanTraj > {
  static const char* value()
  {
    return "bulletsim_msgs/PlanTraj";
  }

  static const char* value(const ::bulletsim_msgs::PlanTraj&) { return value(); }
};


// service_traits::MD5Sum< ::bulletsim_msgs::PlanTrajRequest> should match
// service_traits::MD5Sum< ::bulletsim_msgs::PlanTraj >
template<>
struct MD5Sum< ::bulletsim_msgs::PlanTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bulletsim_msgs::PlanTraj >::value();
  }
  static const char* value(const ::bulletsim_msgs::PlanTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bulletsim_msgs::PlanTrajRequest> should match
// service_traits::DataType< ::bulletsim_msgs::PlanTraj >
template<>
struct DataType< ::bulletsim_msgs::PlanTrajRequest>
{
  static const char* value()
  {
    return DataType< ::bulletsim_msgs::PlanTraj >::value();
  }
  static const char* value(const ::bulletsim_msgs::PlanTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bulletsim_msgs::PlanTrajResponse> should match
// service_traits::MD5Sum< ::bulletsim_msgs::PlanTraj >
template<>
struct MD5Sum< ::bulletsim_msgs::PlanTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bulletsim_msgs::PlanTraj >::value();
  }
  static const char* value(const ::bulletsim_msgs::PlanTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bulletsim_msgs::PlanTrajResponse> should match
// service_traits::DataType< ::bulletsim_msgs::PlanTraj >
template<>
struct DataType< ::bulletsim_msgs::PlanTrajResponse>
{
  static const char* value()
  {
    return DataType< ::bulletsim_msgs::PlanTraj >::value();
  }
  static const char* value(const ::bulletsim_msgs::PlanTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_PLANTRAJ_H
