// Generated by gencpp from file bulletsim_msgs/PlanTrajRequest.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_PLANTRAJREQUEST_H
#define BULLETSIM_MSGS_MESSAGE_PLANTRAJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct PlanTrajRequest_
{
  typedef PlanTrajRequest_<ContainerAllocator> Type;

  PlanTrajRequest_()
    : side()
    , start_joints()
    , end_joints()
    , joint_states()  {
    }
  PlanTrajRequest_(const ContainerAllocator& _alloc)
    : side(_alloc)
    , start_joints(_alloc)
    , end_joints(_alloc)
    , joint_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _side_type;
  _side_type side;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _start_joints_type;
  _start_joints_type start_joints;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _end_joints_type;
  _end_joints_type end_joints;

   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_states_type;
  _joint_states_type joint_states;





  typedef boost::shared_ptr< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanTrajRequest_

typedef ::bulletsim_msgs::PlanTrajRequest_<std::allocator<void> > PlanTrajRequest;

typedef boost::shared_ptr< ::bulletsim_msgs::PlanTrajRequest > PlanTrajRequestPtr;
typedef boost::shared_ptr< ::bulletsim_msgs::PlanTrajRequest const> PlanTrajRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator2> & rhs)
{
  return lhs.side == rhs.side &&
    lhs.start_joints == rhs.start_joints &&
    lhs.end_joints == rhs.end_joints &&
    lhs.joint_states == rhs.joint_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b2b64c83dc990158ae6e041531366b4";
  }

  static const char* value(const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b2b64c83dc99015ULL;
  static const uint64_t static_value2 = 0x8ae6e041531366b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/PlanTrajRequest";
  }

  static const char* value(const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string side\n"
"float64[] start_joints\n"
"float64[] end_joints\n"
"sensor_msgs/JointState joint_states\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.side);
      stream.next(m.start_joints);
      stream.next(m.end_joints);
      stream.next(m.joint_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanTrajRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::PlanTrajRequest_<ContainerAllocator>& v)
  {
    s << indent << "side: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.side);
    s << indent << "start_joints[]" << std::endl;
    for (size_t i = 0; i < v.start_joints.size(); ++i)
    {
      s << indent << "  start_joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.start_joints[i]);
    }
    s << indent << "end_joints[]" << std::endl;
    for (size_t i = 0; i < v.end_joints.size(); ++i)
    {
      s << indent << "  end_joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.end_joints[i]);
    }
    s << indent << "joint_states: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.joint_states);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_PLANTRAJREQUEST_H
