// Generated by gencpp from file bulletsim_msgs/Rope.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_ROPE_H
#define BULLETSIM_MSGS_MESSAGE_ROPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct Rope_
{
  typedef Rope_<ContainerAllocator> Type;

  Rope_()
    : header()
    , nodes()
    , radius(0.0)  {
    }
  Rope_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nodes(_alloc)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _nodes_type;
  _nodes_type nodes;

   typedef float _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::bulletsim_msgs::Rope_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::Rope_<ContainerAllocator> const> ConstPtr;

}; // struct Rope_

typedef ::bulletsim_msgs::Rope_<std::allocator<void> > Rope;

typedef boost::shared_ptr< ::bulletsim_msgs::Rope > RopePtr;
typedef boost::shared_ptr< ::bulletsim_msgs::Rope const> RopeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::Rope_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::Rope_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::Rope_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::Rope_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.nodes == rhs.nodes &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::Rope_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::Rope_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::Rope_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::Rope_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::Rope_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::Rope_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::Rope_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::Rope_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::Rope_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23c934bbc61453e4da5d74059cea6541";
  }

  static const char* value(const ::bulletsim_msgs::Rope_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23c934bbc61453e4ULL;
  static const uint64_t static_value2 = 0xda5d74059cea6541ULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::Rope_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/Rope";
  }

  static const char* value(const ::bulletsim_msgs::Rope_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::Rope_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point[] nodes\n"
"float32 radius\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bulletsim_msgs::Rope_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::Rope_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nodes);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rope_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::Rope_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::Rope_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_ROPE_H
