// Generated by gencpp from file bulletsim_msgs/TrackedObject.msg
// DO NOT EDIT!


#ifndef BULLETSIM_MSGS_MESSAGE_TRACKEDOBJECT_H
#define BULLETSIM_MSGS_MESSAGE_TRACKEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <bulletsim_msgs/Rope.h>
#include <bulletsim_msgs/Box.h>
#include <bulletsim_msgs/Mesh.h>

namespace bulletsim_msgs
{
template <class ContainerAllocator>
struct TrackedObject_
{
  typedef TrackedObject_<ContainerAllocator> Type;

  TrackedObject_()
    : header()
    , type()
    , rope()
    , box()
    , mesh()  {
    }
  TrackedObject_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(_alloc)
    , rope(_alloc)
    , box(_alloc)
    , mesh(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef  ::bulletsim_msgs::Rope_<ContainerAllocator>  _rope_type;
  _rope_type rope;

   typedef  ::bulletsim_msgs::Box_<ContainerAllocator>  _box_type;
  _box_type box;

   typedef  ::bulletsim_msgs::Mesh_<ContainerAllocator>  _mesh_type;
  _mesh_type mesh;





  typedef boost::shared_ptr< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObject_

typedef ::bulletsim_msgs::TrackedObject_<std::allocator<void> > TrackedObject;

typedef boost::shared_ptr< ::bulletsim_msgs::TrackedObject > TrackedObjectPtr;
typedef boost::shared_ptr< ::bulletsim_msgs::TrackedObject const> TrackedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bulletsim_msgs::TrackedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bulletsim_msgs::TrackedObject_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::TrackedObject_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.rope == rhs.rope &&
    lhs.box == rhs.box &&
    lhs.mesh == rhs.mesh;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bulletsim_msgs::TrackedObject_<ContainerAllocator1> & lhs, const ::bulletsim_msgs::TrackedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bulletsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd87acde2b5badaac900f58278c67de6";
  }

  static const char* value(const ::bulletsim_msgs::TrackedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd87acde2b5badaaULL;
  static const uint64_t static_value2 = 0xc900f58278c67de6ULL;
};

template<class ContainerAllocator>
struct DataType< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bulletsim_msgs/TrackedObject";
  }

  static const char* value(const ::bulletsim_msgs::TrackedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string type\n"
"Rope rope\n"
"Box box\n"
"Mesh mesh\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Rope\n"
"Header header\n"
"geometry_msgs/Point[] nodes\n"
"float32 radius\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Box\n"
"geometry_msgs/Point center\n"
"geometry_msgs/Point extents\n"
"float32 angle\n"
"\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Mesh\n"
"geometry_msgs/Point[] vertices\n"
"geometry_msgs/Point[] normals\n"
"Face[] faces\n"
"================================================================================\n"
"MSG: bulletsim_msgs/Face\n"
"uint32[] vertex_inds\n"
"uint32[] normal_inds\n"
;
  }

  static const char* value(const ::bulletsim_msgs::TrackedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.rope);
      stream.next(m.box);
      stream.next(m.mesh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bulletsim_msgs::TrackedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bulletsim_msgs::TrackedObject_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "rope: ";
    s << std::endl;
    Printer< ::bulletsim_msgs::Rope_<ContainerAllocator> >::stream(s, indent + "  ", v.rope);
    s << indent << "box: ";
    s << std::endl;
    Printer< ::bulletsim_msgs::Box_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
    s << indent << "mesh: ";
    s << std::endl;
    Printer< ::bulletsim_msgs::Mesh_<ContainerAllocator> >::stream(s, indent + "  ", v.mesh);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BULLETSIM_MSGS_MESSAGE_TRACKEDOBJECT_H
