(cl:defpackage bulletsim_msgs-srv
  (:use )
  (:export
   "GETTABLE"
   "<GETTABLE-REQUEST>"
   "GETTABLE-REQUEST"
   "<GETTABLE-RESPONSE>"
   "GETTABLE-RESPONSE"
   "INITIALIZATION"
   "<INITIALIZATION-REQUEST>"
   "INITIALIZATION-REQUEST"
   "<INITIALIZATION-RESPONSE>"
   "INITIALIZATION-RESPONSE"
   "PLANTRAJ"
   "<PLANTRAJ-REQUEST>"
   "PLANTRAJ-REQUEST"
   "<PLANTRAJ-RESPONSE>"
   "PLANTRAJ-RESPONSE"
  ))

